name: Deployment of React
on: issues
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@4
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Test the code
              run: npm run test
            - name: Build the code
              run: npm run build
            - name: Deploy the code
              run: echo "Deploying the code into EKS...."