name: Deploy the application
on: push
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: npm ci
            - name: Lint the code
              run: npm run lint
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v4
            - name: Install dependencies
              uses: npm ci
            - name: Test the code
              run: npm run test
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install dependencies
              uses: npm ci
            - name: Build code
              uses: npm run build
            - name: Deploy code
              uses: echo "Deploying....."
